### ISSUE TITLE
遇到两个问题

### ISSUE THREAD

**Issue by chengyiqun** [davidkane0526/Dnest#1]
[Dnest 0.9.7](https://github.com/davidkane0526/Dnest/releases/tag/V0.9.7)

1. 在设置了托盘图标自动隐藏的时候, 把Dnest图标从隐藏托盘里拖到外面显示, 下次启动时, Dnest的图标还是隐藏托盘的.
2. 不能记住Dnest面板显示的位置, 重启后消失了, 偶尔点不开. 顺便一提, 我是2k分辨率屏幕.

**Comment by davidkane0526** [comment]
需要记住面板位置可以在设置中点击 当前位置 ，这样下次启动就会在设定位置启动
关于托盘问题我研究一下

**Comment by davidkane0526** [comment]
下个版本更新为 设置中选择 当前位置 后，系统退出是默认保存当前位置
