### ISSUE TITLE
关于锁定文件的问题

### ISSUE THREAD

**Issue by Night8848** [davidkane0526/Dnest#3]
- 试用了下“锁定文件“这个功能，发现拖走文件后只能留一个空壳图标在原地，并不能对其再次进行操作。
我比较期待的效果是：未锁定时拖放文件使用”移动“，锁定时拖放文件执行”复制“。

- 另外建议添加清空所有项目的按钮，或者右键选项。

**Comment by davidkane0526** [comment]
1. 因为是移动了文件，所以原始路径失效了，下个版本会修复，你的建议不错，下个版本会加进去，这样逻辑比较统一；
2. 在开发版本已经加入了常用快捷键 ctrl+A，或者你可以在现在版本中框选全部文件然后右键菜单中“删除文件”，此时选中的文件就都会删除；
3. 下个版本会考虑将右键菜单“删除文件”在选中多个文件时显示为“删除所选文件”这样可能会更加清晰，锁定和解锁文件也会做相似修改；
4. 感谢 comment；

**Comment by Night8848** [comment]
> * 因为是移动了文件，所以原始路径失效了，下个版本会修复，你的建议不错，下个版本会加进去，这样逻辑比较统一；
> * 在开发版本已经加入了常用快捷键 ctrl+A，或者你可以在现在版本中框选全部文件然后右键菜单中“删除文件”，此时选中的文件就都会删除；
> * 下个版本会考虑将右键菜单“删除文件”在选中多个文件时显示为“删除所选文件”这样可能会更加清晰，锁定和解锁文件也会做相似修改；
> * 感谢 comment；

感谢回复，软件很好用，期待更新。
